using UnityEngine;

public class PersistentSingleton<T> : MonoBehaviour where T : Component
{
    private static T _instance;
    public static T Instance
    {
        get
        {
            // 如果实例不存在，尝试在场景中查找
            if (_instance == null)
            {
                _instance = FindObjectOfType<T>();
                // 如果仍然找不到，自动创建一个新的 GameObject
                if (_instance == null)
                {
                    GameObject obj = new GameObject(typeof(T).Name + "_AutoGenerated");
                    _instance = obj.AddComponent<T>();
                }
            }
            return _instance;
        }
    }

    protected virtual void Awake()
    {
        // 如果实例已存在且不是当前对象，则销毁自身
        if (_instance != null && _instance != this)
        {
            Destroy(gameObject);
            return;
        }

        // 设置为单例实例，并标记为跨场景不销毁
        _instance = this as T;
        DontDestroyOnLoad(gameObject);

        // 可选：防止在编辑器中误删
#if UNITY_EDITOR
        gameObject.hideFlags = HideFlags.NotEditable;
#endif
    }

    // 防止通过 Destroy 删除对象
    private void OnDestroy()
    {
        if (_instance == this)
        {
            _instance = null;
            Debug.LogWarning("单例实例被销毁！请确保不要手动调用 Destroy。");
        }
    }
}